# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for hardly
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
  tasks:
    # - import_tasks: tasks/process-source-branch.yaml
    - name: Install all RPM/python packages needed to run hardly
      ansible.builtin.dnf:
        name:
          - centpkg
          - tig # for debugging, can be removed later
