# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: This is a recipe for a container image where hardly tests will run
  hosts: all
  tasks:
    - name: Install test RPM dependencies
      ansible.builtin.dnf:
        name:
          - python3-pytest
          - python3-pytest-cov
        state: present
    - name: Install pip deps
      ansible.builtin.pip:
        name:
          - flexmock # RHBZ#2120251
